site_name: XUJG Site
site_url: https://xjg-0216.github.io
site_author: xujg
site_description: XUJG Site

# [Navigation]
nav:
  - GIT:
    - GIT/01-git-basics.md
    - GIT/02-git-branch.md
    - GIT/03-git-remote.md
    - GIT/04-git-lfs.md
  - 工具:
    - 系统管理:
      - TOOL/system/01-apt.md
      - TOOL/system/02-proxy.md
      - TOOL/system/03-mount.md
      - TOOL/system/04-tar.md
    - Docker:
      - TOOL/docker/01-docker-install.md
      - TOOL/docker/02-docker-commands.md
    - 远程操作:
      - TOOL/remote/01-scp-rsync.md
      - TOOL/remote/02-byobu.md
    - 开发环境:
      - TOOL/dev/conda.md
      - TOOL/dev/vscode-remote-auto-conn.md
    - RK3588:
      - TOOL/rk3588.md
  - C++:
    - 编译工具链:
      - C++/vscode/00-make.md
      - C++/vscode/01-g++.md
      - C++/vscode/02-compile.md
      - C++/vscode/03-dbg.md
      - C++/vscode/04-debug.md
      - C++/vscode/05-cmake.md
      - C++/vscode/06-cmake-compile-step.md
      - C++/vscode/07-cmake-compile.md
      - C++/vscode/08-vscode-debug.md
      - C++/vscode/09-vscode-appendix.md
    - 语法:
      - C++/00-stl.md
      - C++/01-class1.md
      - C++/02-class2.md
      - C++/03-class3.md
      - C++/04-memory.md
      - C++/05-argv.md
      - C++/06-char.md
      - C++/07-const.md
      - C++/08-point_reference.md
      - C++/09-type_modify.md
      - C++/10-type_convert.md
      - C++/11-define.md
      - C++/12-multi_thread.md
      - C++/13-lambda.md
      - C++/14-linking.md
      - C++/15-std_function.md
      - C++/16-l_r_value.md
      - C++/17-function_template.md
      - C++/18-std_bind.md
      - C++/19-std_result_of.md
      - C++/20-std_packaged_task.md
      - C++/21-hdf5.md
      - C++/22-question.md
      - C++/23-read.md
  - 传统图像处理:
    - classical-cv/01-isp-pipeline.md
    - classical-cv/02-opencv-mat.md
    - classical-cv/03-imaging-basics.md
  - 深度学习基础:
    - deep-learning/01-transformer.md
    - deep-learning/02-ViT.md
    - deep-learning/03-bert.md
    - deep-learning/04-mae.md
    - deep-learning/05-gpt.md
    - deep-learning/06-rnn_lstm.md
    - deep-learning/07-DDPM.md
    - deep-learning/08-bigram.md
  - 算法:
    - LLM:
      - algorithms/llm/00-LLM学习路线.md
      - algorithms/llm/03-ollama使用.md
      - algorithms/llm/06-miniGPT.md
      - algorithms/llm/07-nanoGPT.md
      - algorithms/llm/08-mfu.md
      - RAG:
        - algorithms/llm/rag/01-rag-setup-overview.md
        - algorithms/llm/rag/02-rag-multi-query.md
        - algorithms/llm/rag/03-rag-routing-query.md
        - algorithms/llm/rag/04-rag-indexing-retrieval.md
        - algorithms/llm/rag/05-rag-retrieval-reranking.md
    - 计算机视觉:
      - algorithms/cv/01-bytetrack.md
      - algorithms/cv/02-netvlad.md
  - 模型部署:
    - deploy/01-rknn.md
    - deploy/02-onnx.md

# [UI]
# [top]

theme:
  name: material
  # [切换日间模式和夜间模式]
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle
  palette:
    # 日间模式
    - scheme: default
      # 主颜色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
      primary: indigo
      # 链接等可交互元件的高亮色
      # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
      accent: orange
      toggle:
        # 图标
        icon: material/weather-night
        # 鼠标悬浮提示
        name: 切换至夜间模式
    # 夜间模式
    - scheme: slate
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    # 使用 Tab 来进行分类
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # 返回顶部的按钮，在上滑时出现
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # 给每个 Tab 添加一个 index.md，且在点击 Tab 时打开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # 打开 Tab 时左侧目录全部展开
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    - navigation.expand
    # 搜索输入一些字母时推荐补全整个单词
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # 搜索的关键词文章加入高亮
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # 可以通过按钮复制代码
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [点击按钮跳转至 GitHub 修改 Markdown 源文件]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # 痕迹导航
    - navigation.path
  language: zh # 一些提示性的文字会变成中文
  icon:
    # [添加 GitHub 仓库]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
# [点击按钮跳转至 GitHub 修改 Markdown 源文件]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [添加 GitHub 仓库]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Xjg-0216/xjg-0216.github.io
repo_name: xjg-0216.github.io



# [Extensions]
plugins:
  # [搜索功能]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # 之前中文搜索是 Insider 的功能（https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/），现在好像已经是默认功能了，
  - search:
      lang:
        - zh
        - en
        - ja
  # [给单篇文章添加标签]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags
  # - social
markdown_extensions:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - pymdownx.arithmatex:
      generic: true
  # [图片功能支持]
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  # 给 Markdown 图片语法后面添加 `{width="300"}` 设置大小
  - attr_list
  - md_in_html
  # [给标题添加链接]
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#+toc.permalink
  - toc:
      permalink: true # 固定标题位置为当前位置
  # [代码语法高亮]
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-blocks
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#highlight
  - pymdownx.highlight:
      # 显示行号
      linenums: true
      # 显示编程语言名称
      auto_title: true
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.line_spans
      line_spans: __span
      # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#+pymdownx.highlight.pygments_lang_class
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # [Markdown 提示]
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # [Markdown footnote 语法支持]
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - pymdownx.tilde  # 支持删除线
  - pymdownx.mark  # 支持背景高亮
  - tables  # 改进表格显示
  # - abbr  # 支持扩展引用块
  - def_list  # 支持定义列表
  # - smartypants  # 智能引用
  - pymdownx.emoji  # 支持Emoji
  # - autolink  # 自动将URL转换为链接
  # - headerid  # 为标题添加锚点
  # - pymdownx.charts  # 支持插入图表
  # - tasklist  # 支持任务列表语法
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  # # [自定义 css]
  # # 不使用底部的翻页
  - mkdocs/css/no-footer.css
  # # 无序列表符号自定义
  # - mkdocs/css/unordered-list-symbols.css
